service: rsvp-updates
frameworkVersion: '3'

package:
  exclude:
    - node_modules/**
    - __pycache__/**

custom:
  myEnv: ${file(env/variables.dev.yml)}
  pythonRequirements:
    noDeploy: []
    dockerizePip: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  region: ${opt:region, "ap-southeast-1"}
  architecture: arm64

functions:
  handle_request:
    handler: handler.handle_request
    memorySize: 128
    timeout: 120
    events:
      - schedule: cron(0 * * * ? *)
    environment:
      telegram_token: ${self:custom.myEnv.telegramToken}
      chat_id: ${self:custom.myEnv.chatId}
      supabase_url: ${self:custom.myEnv.supabaseUrl}
      supabase_key: ${self:custom.myEnv.supabaseKey}
